# AWS Provider
aws:
  # provider_version: "~> 3.52.0"

  # Backend configuration
  backend_bucket: "terraform-tfstate"
  backend_lock: "terraform-tflock"

  # Common configuration
  default_region: ap-northeast-1
